name: CDE Workflow - pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  RunUnitTest:
    name: Unit Test (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      GOPRIVATE: github.com/AquaRepos/*
      GO111MODULE: on
    strategy:
      matrix:
        go-version: ["1.23"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#        with:
#          persist-credentials: true
#      - name: Configure Git for private modules
#        env:
#          TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download dependencies
        run: go mod download
      - name: Run Unit Test
        run: go test ./...
  ValidateBranchName:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name Includes Ticket Number
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" =~ (feature|bugfix|hotfix|release|revert)\/CDE-[0-9]+[-\/\_].* ]]; then
            echo "Branch name includes ticket";
          else
            echo "Branch name doesn't include ticket";
            exit 1;
          fi